name: check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: install
        run: |
          curl -fsSL https://cli.moonbitlang.com/install/unix.sh | bash
          echo "$HOME/.moon/bin" >> $GITHUB_PATH

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "yarn"

      - name: moon check
        run: moon update && moon check

      # - name: moon info
      #   run: |
      #     moon info
      #     git diff --exit-code

      - name: moon test
        run: |
          moon build --target js --debug

      - name: "compiles to js"
        run: yarn && yarn vite build --base=./

      # - name: moon bundle
      #   run: moon bundle

      # - name: check core size
      #   run: ls -alh `find ./target/bundle -name *.core`

      # - name: format diff
      #   run: |
      #     moon fmt
      #     git diff

      - name: Deploy to server
        id: deploy
        uses: Pendect/action-rsyncer@v2.0.0
        env:
          DEPLOY_KEY: ${{secrets.rsync_private_key}}
        with:
          flags: "-avzr --progress"
          options: ""
          ssh_options: ""
          src: "dist/*"
          dest: "rsync-user@tiye.me:/web-assets/repo/${{ github.repository }}"

      - name: Display status from deploy
        run: echo "${{ steps.deploy.outputs.status }}"
